### PR TITLE
Add testing info in readme; change 'install' to 'develop'

### PR DESCRIPTION
**Pull request by maxking**
Its generally a good idea to use 'develop' when developing inside
of a virtualenv instead of 'install'.

### CODE REVIEW

**Comment by mythmon** [comment]
Cool, thanks.

In the future, this is generally easier when you work on a separate branch, instead of on master. If that were the case, you could destroy the branch locally, recreate it with the correct set of commits, and force push that to the branch that the PR was made from on GitHub. That way you don't have to make multiple PRs.

**Comment by maxking** [comment]
@mythmon I try to avoid force-push even when I know what I am doing. Have had bad experiences with it. I'd rather delete the branch oh Github and re-create it.

**Comment by mythmon** [comment]
Deleting the branch and recreating it is the same as force pushing now. `git push --force` in Git 2.0 only deals with the current branch, so it is a lot safer than it used to be (where it had the potential of overwriting other branches). Another helpful thing is `git push --force-with-lease` which will only override a branch if the remote's current branch matches what your local records expect it to be. That avoids overwriting other people's changes. Though you won't often get that if you work on a personal branch.

**Comment by maxking** [comment]
Cool, thanks!

**Pull request merged**
